services:
  nginx:
     image: nginx:latest
     container_name: reverse_proxy
     volumes:
         - ./nginx/templates/default.conf.ssl.template:/etc/nginx/templates/default.conf.template
         - ./nginx/templates:/etc/nginx/templates
         - ./container_logs/nginx:/var/log/nginx
         - ./secrets/nginx:/etc/ssl
         - ./public_html:/usr/share/nginx/html
     ports:
         - "80:80"
         - "443:443"
     environment:
        - NGINX_PORT=80
        - NGINX_SSL_PORT=443
        - NGINX_PROXY=http://application:3002
        - NGINX_CERT_DIR=/etc/ssl
        - NGINX_CERT=server.crt
        - NGINX_KEY=server.key
        - NGINX_HOST=localhost
#        - NGINX_SSL_PORT=443
#        - NGINX_ENTRYPOINT_QUIET_LOGS=1
     depends_on:
         - application
     restart: always

  application:
    build: 
      context: .
      dockerfile: Dockerfile
    #image: node:current
    #image: wt1-express-local
    #build:
    #  context: .
    #  dockerfile: Dockerfile
    ports:
      - "3002:3002"
    volumes:
      - ./:/home/node/
    #command: "npm start"